### ISSUE TITLE
Cannot run basic setup

### ISSUE THREAD

**Issue by rauwebieten** [panlatent/element-generator#1]
Tried a basic setup.

Config:

```
<?php

use craft\elements\Entry;
use panlatent\craft\element\generator\value\Context;

return [
    'generators' => [
        'default' => [],
        'ads' => function () {
            return [
                'elementType' => Entry::class,
                'section' => 'ad',
                'values' => function (Context $ctx) {
                    return [
                        'title' => $ctx->faker->company(),
                    ];
                },
            ];
        },
    ],
];
```

("ad" is a valid section)

Ran the command
`php craft gen ads`

But got an error:

```
[Exception 'yii\base\InvalidConfigException' with message ''

in /var/www/vendor/panlatent/element-generator/src/models/Settings.php:38

Stack trace:
#0 /var/www/vendor/panlatent/element-generator/src/services/Generators.php(41): panlatent\craft\element\generator\models\Settings->getGenerators()
#1 /var/www/vendor/panlatent/element-generator/src/services/Generators.php(48): panlatent\craft\element\generator\services\Generators->getAllGenerators()
#2 /var/www/vendor/panlatent/element-generator/src/console/controllers/GeneratorsController.php(73): panlatent\craft\element\generator\services\Generators->getGeneratorByName()
#3 [internal function]: panlatent\craft\element\generator\console\controllers\GeneratorsController->actionGenerate()
#4 /var/www/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#5 /var/www/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams()
#6 /var/www/vendor/yiisoft/yii2/console/Controller.php(180): yii\base\Controller->runAction()
#7 /var/www/vendor/yiisoft/yii2/base/Module.php(552): yii\console\Controller->runAction()
#8 /var/www/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction()
#9 /var/www/vendor/craftcms/cms/src/console/Application.php(91): yii\console\Application->runAction()
#10 /var/www/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction()
#11 /var/www/vendor/craftcms/cms/src/console/Application.php(122): yii\console\Application->handleRequest()
#12 /var/www/vendor/yiisoft/yii2/base/Application.php(384): craft\console\Application->handleRequest()
#13 /var/www/craft(13): yii\base\Application->run()
#14 {main}](url)
```

PHP 8.1.23
Craft Pro 4.10.2
Element Generator | 1.0.0

**Comment by rauwebieten** [comment]
Fixed it by removing 

`'default' => [],`

from the config file.
Maybe update your docs?

**Comment by panlatent** [comment]
@rauwebieten  Thank!  This is a documentation example error, key `default` is at the outermost level
